name: Create Board Firmware

on:
  schedule:
    - cron: '10 17 * * *' # build fresh every 5:10 PM
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: chuckwagoncomputing/rusefi/.github/workflows/custom-board-build.yaml@makeover-bundle
    secrets: inherit
    permissions:
      contents: write
    with:
      shortBoardName: paralela
      rusefi_dir: ext/rusefi
      relative_board_dir: ../..
